pipeline {
    agent any

    environment {
      gatlingTestBaseURL = 'https://www.amazon.com/'
      gatlingNumberOfUsers = '2'
      gatlingTestDurationMinutes = '1'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                echo 'available enverionment variables'
                sh "printenv | sort"
            }
        }
        stage('Load Test') {
            steps {
                sh "./gradlew -S -info --no-daemon testLoad"
            }
            post {
                always {
                    gatlingArchive()
                }
                unstable {
                    echo 'unstable'
                }
                failure {
                    echo 'failure'
                }
                success {
                    echo 'success'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}